### ISSUE TITLE
의상 예약 상태 추가

### ISSUE THREAD

**Issue by yejin9858** [pick-PICKLE/PICKLE_Server#45]
## ☝️  Issue
- 의상 예약 상태 추가하기
- dress list에 isLiked 추가하기
- dress 검색 범위 변경

## 📃 To-do

- [x] 의상 예약 상태 추가하기
- [x] dress list에 isLiked 추가하기
- [ ] dress 검색 범위 변경
